[package]
name = "struktur-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
struktur-core = { path = "../struktur-core" }
tokio = { version = "1.53.1", features = ["full"] }
